services:
  streetmerchant:
    image: ghcr.io/alex-bue/streetmerchant:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streetmerchant
    volumes:
      - ./src:/app/src
      - ./web:/app/web
      - ./.env:/app/.env
      - ./test:/app/test
    env_file:
      - dotenv
